name: openpay-php
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openpay-php
    working_dir: /app
    volumes:
      - .:/app
      - composer-cache:/root/.composer/cache
      - coverage-data:/app/coverage
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: ["tail", "-f", "/dev/null"]

volumes:
  composer-cache:
  coverage-data:
